import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import StoreProvider from "@/lib/provider";

import "./globals.css";

const noto_sans_jp = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_sans_jp.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
